import "../styles/globals.css";
import "highlight.js/styles/github-dark.css";

export const metadata = {
  title: "Projects | Blake Wilson - Software Engineer and Creator" ,
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
